import pandas as pd

def get_movies_df():
    """
    Returns a DataFrame with 300 movies.
    100 English + 100 Hindi + 100 Telugu
    To ADD more movies: just add to the lists below!
    """

    # ── ENGLISH MOVIES (100) ───────────────────────────────────────────
    english = [
        # title,                              genre,                      description,                                                        rating
        ("The Dark Knight",                   "Action Crime Drama Thriller",    "Batman faces the Joker in an epic battle of good vs evil",         9.0),
        ("Inception",                         "Action Sci-Fi Thriller",         "A thief enters dreams to steal secrets from the subconscious",     8.8),
        ("Interstellar",                      "Adventure Drama Sci-Fi",         "Astronauts travel through a wormhole to find humanitys new home",  8.6),
        ("The Matrix",                        "Action Sci-Fi",                  "A hacker discovers the world is a simulation and joins rebels",     8.7),
        ("Avengers Endgame",                  "Action Adventure Sci-Fi",        "Superheroes assemble to undo the destruction of half the universe", 8.4),
        ("Iron Man",                          "Action Adventure Sci-Fi",        "Billionaire Tony Stark builds an armor suit to save the world",    7.9),
        ("Spider-Man No Way Home",            "Action Adventure Sci-Fi",        "Spider-Man faces multiverse villains after his identity is revealed",8.2),
        ("The Godfather",                     "Crime Drama",                    "The patriarch of a crime dynasty transfers power to his son",       9.2),
        ("Pulp Fiction",                      "Crime Drama Thriller",           "Criminals in Los Angeles intertwine in four tales of violence",     8.9),
        ("Fight Club",                        "Drama Thriller",                 "An insomniac forms an underground fight club with a stranger",      8.8),
        ("Titanic",                           "Drama Romance",                  "A young aristocrat falls in love with a poor artist on the Titanic",7.8),
        ("The Notebook",                      "Drama Romance",                  "A man writes the story of young love between a rich and poor pair", 7.9),
        ("La La Land",                        "Drama Music Romance",            "A pianist and actress fall in love while pursuing dreams in LA",    8.0),
        ("The Lion King",                     "Animation Adventure Family",     "A young lion prince flees after his father is murdered by his uncle",8.5),
        ("Toy Story",                         "Animation Adventure Comedy",     "A cowboy toy is threatened when a spaceman becomes the new favorite",8.3),
        ("Finding Nemo",                      "Animation Adventure Comedy",     "A clownfish crosses the ocean to find his son taken by a diver",    8.1),
        ("Up",                                "Animation Adventure Drama",      "An elderly man sees South America in a floating balloon house",      8.1),
        ("The Shining",                       "Drama Horror Thriller",          "A family in an isolated hotel is terrorized by supernatural forces", 8.4),
        ("Get Out",                           "Horror Mystery Thriller",        "A Black man visits his white girlfriend parents and finds secrets",  7.7),
        ("A Quiet Place",                     "Drama Horror Thriller",          "A family survives in a world where monsters hunt by sound",          7.5),
        ("The Hangover",                      "Comedy",                         "Three friends wake up after a bachelor party with no memory",        7.7),
        ("Knives Out",                        "Comedy Crime Mystery",           "A detective investigates a crime novelists death at a gathering",    7.9),
        ("Superbad",                          "Comedy",                         "Two high school friends plan a big night before prom",              7.6),
        ("Avatar",                            "Action Adventure Sci-Fi",        "A marine on Pandora must choose between orders and protecting aliens",7.8),
        ("Gravity",                           "Drama Sci-Fi Thriller",          "Two astronauts survive after an accident leaves them adrift in space",7.7),
        ("The Martian",                       "Adventure Drama Sci-Fi",         "An astronaut stranded on Mars must find a way to survive and return",8.0),
        ("Arrival",                           "Drama Mystery Sci-Fi",           "A linguist is recruited to communicate with extraterrestrial visitors",7.9),
        ("Ex Machina",                        "Drama Sci-Fi Thriller",          "A programmer questions whether his AI assistant has become sentient", 7.7),
        ("Parasite",                          "Drama Thriller",                 "A poor family schemes to work their way into a wealthy household",   8.5),
        ("Joker",                             "Crime Drama Thriller",           "A troubled comedian spirals downward and becomes Batman nemesis",    8.4),
        ("1917",                              "Drama History War",              "Two soldiers cross enemy territory to deliver a critical message",   8.3),
        ("Schindlers List",                   "Biography Drama History",        "A businessman saves Jewish factory workers lives during the Holocaust",9.0),
        ("The Shawshank Redemption",          "Drama",                          "A wrongly convicted man finds hope through friendship in prison",    9.3),
        ("Forrest Gump",                      "Drama Romance Comedy",           "A man with low IQ experiences American history through coincidences", 8.8),
        ("Goodfellas",                        "Crime Drama",                    "A young man rises through the ranks of the Italian American mob",    8.7),
        ("The Silence of the Lambs",          "Crime Thriller Horror",          "An FBI agent tracks a serial killer with help of another killer",    8.6),
        ("No Country for Old Men",            "Crime Drama Thriller",           "A ruthless hitman pursues a thief across the American Southwest",    8.1),
        ("Whiplash",                          "Drama Music",                    "A music student is pushed to limits by an obsessive instructor",     8.5),
        ("Birdman",                           "Comedy Drama",                   "A Hollywood actor struggling with fame transforms into his character",7.7),
        ("Mad Max Fury Road",                 "Action Sci-Fi",                  "A road warrior fights across a post apocalyptic wasteland",          8.1),
        ("Logan",                             "Action Drama Sci-Fi",            "A mutant hero faces his final mission protecting young mutants",      8.1),
        ("Black Panther",                     "Action Adventure Sci-Fi",        "A young African king defends his kingdom using advanced technology",  7.3),
        ("Doctor Strange",                    "Action Adventure Fantasy",       "A sorcerer learns mystic arts to defend reality from supernatural threats",7.5),
        ("Thor Ragnarok",                     "Action Comedy Sci-Fi",           "A prince stages a revolution with help from the Incredible Hulk",    7.9),
        ("Guardians of the Galaxy",           "Action Comedy Sci-Fi",           "Misfit outlaws protect the galaxy from a powerful enemy",            8.0),
        ("Captain America Civil War",         "Action Sci-Fi",                  "The Avengers are divided over government oversight as a new threat emerges",7.8),
        ("Deadpool",                          "Action Comedy",                  "A mercenary with healing powers becomes a wisecracking anti hero",   8.0),
        ("John Wick",                         "Action Thriller",                "A retired hitman returns to the underworld after his dog is killed",  7.4),
        ("The Bourne Identity",               "Action Thriller Spy",            "A CIA officer hunted by assassins discovers his past as a trained killer",7.9),
        ("Mission Impossible Fallout",        "Action Thriller Spy",            "An IMF agent must stop a deadly virus from being sold to terrorists", 7.7),
        ("Top Gun Maverick",                  "Action Drama",                   "A legendary Navy pilot trains new recruits for one final mission",    8.2),
        ("Die Hard",                          "Action Thriller",                "A New York cop battles terrorists who take over a skyscraper",        8.2),
        ("Speed",                             "Action Thriller",                "A bus rigged to explode if it drops below fifty miles per hour",      7.3),
        ("The Terminator",                    "Action Sci-Fi",                  "A robotic killer is sent back in time to assassinate a future leader", 8.1),
        ("Jurassic Park",                     "Adventure Sci-Fi",               "Scientists clone dinosaurs and open a theme park that goes wrong",    8.2),
        ("ET",                                "Sci-Fi Family Drama",            "An alien left behind on Earth is befriended by a young boy",          7.9),
        ("Back to the Future",                "Sci-Fi Comedy Adventure",        "A teenager travels back in time to ensure his parents fall in love",   8.5),
        ("Star Wars A New Hope",              "Sci-Fi Action Adventure",        "A young farm boy joins rebels to fight an evil galactic empire",       8.6),
        ("The Lord of the Rings",             "Action Fantasy Adventure",       "A hobbit embarks on an epic quest to destroy a powerful ring",        8.9),
        ("Harry Potter Sorcerers Stone",      "Fantasy Adventure Family",       "A young wizard discovers his heritage and begins training at magic school",7.6),
        ("Pirates of the Caribbean",          "Action Adventure Fantasy",       "A British captain becomes a pirate seeking a legendary treasure",      8.1),
        ("The Avengers",                      "Action Adventure Sci-Fi",        "The Avengers assemble for the first time to fight an alien invasion",  8.0),
        ("Ant-Man",                           "Action Comedy Sci-Fi",           "A thief who shrinks to insect size uses a suit to fight crime",        7.3),
        ("Wonder Woman",                      "Action Fantasy",                 "An Amazon princess leaves her island to fight in the first world war", 7.4),
        ("Aquaman",                           "Action Adventure Fantasy",       "The king of Atlantis fights to protect his underwater kingdom",        6.9),
        ("Batman v Superman",                 "Action Sci-Fi",                  "Batman and Superman clash over their different approaches to heroism",  6.5),
        ("Suicide Squad",                     "Action Adventure",               "Supervillains are recruited by the government for a dangerous mission", 6.0),
        ("Venom",                             "Action Sci-Fi",                  "A journalist bonds with an alien symbiote giving him extraordinary powers",6.5),
        ("The Dark Knight Rises",             "Action Drama",                   "Batman faces a masked villain who seeks to destroy Gotham City",       8.4),
        ("Man of Steel",                      "Action Sci-Fi",                  "Superman arrives on Earth and must choose between his origins and home",6.5),
        ("X-Men",                             "Action Sci-Fi",                  "Mutant heroes fight for coexistence between humans and mutants",       7.4),
        ("Black Widow",                       "Action Thriller",                "A spy confronts her past while fighting a global threat",              6.7),
        ("Eternals",                          "Action Fantasy",                 "Ancient heroes fight celestial beings who shaped human history",       6.3),
        ("Shang-Chi",                         "Action Adventure",               "A martial artist discovers his destiny as a legendary warrior",        7.4),
        ("The Maze Runner",                   "Adventure Sci-Fi",               "Young people trapped in a deadly maze must find a way to escape",      6.8),
        ("The Hunger Games",                  "Action Sci-Fi",                  "A girl volunteers for a deadly annual competition in a dystopian future",7.2),
        ("Ready Player One",                  "Adventure Sci-Fi",               "A man discovers a virtual reality universe where pop culture rules",    7.4),
        ("Edge of Tomorrow",                  "Action Sci-Fi",                  "A soldier relives the same combat mission in a time loop",             7.9),
        ("District 9",                        "Action Sci-Fi",                  "Alien creatures are confined in a camp in South Africa in this thriller",7.9),
        ("Prometheus",                        "Sci-Fi Horror",                  "A crew investigates a distress signal on a distant moon and faces danger",7.0),
        ("Alien",                             "Sci-Fi Horror",                  "Crew members aboard a spacecraft are hunted by a deadly alien creature", 8.5),
        ("The Conjuring",                     "Horror Thriller",                "Paranormal investigators help a family haunted by a demonic entity",    7.5),
        ("It",                                "Horror",                         "A group of children face a terrifying shape shifting clown in their town",7.3),
        ("Hereditary",                        "Horror Drama",                   "A grieving family inherits a disturbing dark secret along with their estate",7.3),
        ("Midsommar",                         "Horror",                         "A couple travels to a Swedish village for a festival with sinister intentions",7.1),
        ("Us",                                "Horror Thriller",                "A family is hunted by shadowy versions of themselves in a thriller",    6.8),
        ("Bird Box",                          "Horror Thriller",                "People are forced to wear blindfolds to avoid supernatural creatures",  6.6),
        ("A Quiet Place Part II",             "Horror Thriller",                "A family continues to survive in a world where monsters hunt by sound", 7.3),
        ("Halloween",                         "Horror Thriller",                "A woman must survive a night in her hometown during a murder spree",    6.5),
        ("Dune",                              "Sci-Fi Adventure",               "A young man journeys to a desert planet to fulfill his destiny",        8.0),
        ("Tenet",                             "Action Sci-Fi Thriller",         "A scientist attempts to reverse time during a global conflict",         7.4),
        ("Oppenheimer",                       "Biography Drama History",        "The life story of physicist Robert Oppenheimer who led the atomic bomb", 8.9),
        ("Barbie",                            "Comedy Fantasy",                 "A doll comes to life and explores the real world with her companion",   6.9),
        ("The Batman",                        "Action Crime Drama",             "A new vigilante Batman fights crime and uncovers a conspiracy in Gotham",7.8),
        ("Everything Everywhere All at Once", "Action Sci-Fi Comedy",           "A woman and her family fight absurdist villains across multiple universes",7.8),
        ("Nope",                              "Horror Sci-Fi",                  "A filmmaker witnesses a strange event in the California desert",        6.8),
        ("Prey",                              "Action Sci-Fi",                  "A young woman fights back against the Predator in the Comanche Nation", 7.1),
        ("Triangle of Sadness",               "Drama Comedy",                   "A wealthy passenger ship becomes the setting for a dark class satire",  7.4),
        ("The Whale",                         "Drama",                          "A man struggles with his sense of self as his body changes dramatically",7.2),
        ("Glass Onion",                       "Comedy Crime Mystery",           "A detective investigates a murder mystery on a private island",         7.2),
    ]

    # ── HINDI MOVIES (100) ────────────────────────────────────────────
    hindi = [
        ("Dangal",                            "Biography Drama Sport",          "A father trains his daughters to become world wrestling champions",     8.4),
        ("3 Idiots",                          "Comedy Drama",                   "Three engineering students challenge the corrupt education system",      8.4),
        ("PK",                                "Comedy Drama Sci-Fi",            "An alien visits Earth and questions human social norms and religion",    8.1),
        ("Dil Chahta Hai",                    "Comedy Drama Romance",           "Three childhood friends rediscover life love and friendship in Goa",     8.1),
        ("Zindagi Na Milegi Dobara",          "Adventure Comedy Drama",         "Three friends take a road trip across Spain discovering love and life",  8.2),
        ("Lagaan",                            "Drama History Sport",            "A village in colonial India challenges British rulers to cricket",        8.1),
        ("Sholay",                            "Action Adventure Drama",         "Two bandit friends fight police and rival gangs in a village",           8.2),
        ("Kabhi Khushi Kabhie Gham",          "Drama Romance Family",           "A wealthy family navigates love separation and reunion across generations",7.4),
        ("Dilwale Dulhania Le Jayenge",       "Drama Romance",                  "A young Punjabi woman falls in love on a Europe trip despite disapproval",8.0),
        ("Taare Zameen Par",                  "Drama Family",                   "A child with dyslexia finds hope through a compassionate art teacher",   8.5),
        ("Andhadhun",                         "Crime Thriller Mystery",         "A piano teacher goes blind and gets embroiled in a murder mystery",      8.3),
        ("Article 15",                        "Crime Drama Thriller",           "A young IPS officer fights caste discrimination and crime in a village", 8.0),
        ("Gangs of Wasseypur",                "Crime Drama Thriller",           "Two rival families engage in bloody gang war in Dhanbad over coal",      8.2),
        ("Queen",                             "Drama",                          "A young woman travels to Berlin for a competition and discovers herself", 7.7),
        ("Tumbbad",                           "Drama Horror",                   "A farmer encounters supernatural forces in his crumbling mansion",        8.0),
        ("Swades",                            "Drama Romance",                  "A scientist returns to his village to help bring water to rural India",   8.2),
        ("Rang De Basanti",                   "Drama History",                  "Young friends question the system after their friend is killed by police",8.2),
        ("Drishyam",                          "Crime Thriller Drama",           "A man protects his family by creating a false alibi after an accident",  8.3),
        ("Bajrangi Bhaijaan",                 "Adventure Drama Romance",        "A devoted Indian man takes a mute Pakistani girl back to her homeland",  8.0),
        ("Sultan",                            "Action Drama Sport",             "A wrestler returns from retirement to fight a world championship match",  7.8),
        ("Bhaag Milkha Bhaag",               "Biography Drama Sport",          "The life of Indian sprinter Milkha Singh who became a national hero",    8.2),
        ("Uri The Surgical Strike",           "Action Thriller",                "Indian special forces carry out a surgical strike across the border",     8.2),
        ("Raazi",                             "Thriller Spy Drama",             "A young woman becomes a spy for India in Pakistan during 1971 war",      7.9),
        ("Kahaani",                           "Thriller Mystery Drama",         "A pregnant woman investigates her missing husband in Kolkata",           7.8),
        ("Mughal-E-Azam",                     "Drama History Romance",          "An emperor falls in love with a courtesan in Mughal India epic drama",   8.0),
        ("Mother India",                      "Drama",                          "A woman sacrifices everything to protect her children and village",       7.8),
        ("Kuch Kuch Hota Hai",               "Drama Romance",                  "Two childhood friends reunite at college and love blossoms",             8.2),
        ("Mohabbatein",                       "Drama Romance",                  "A music teacher inspires students while clashing with tradition",         7.5),
        ("Veer-Zaara",                        "Drama Romance",                  "A man searches across India and Pakistan for his lost wartime love",      8.2),
        ("Kal Ho Naa Ho",                     "Drama Romance",                  "A man discovers he is dying and reconnects with family and friends",      8.0),
        ("My Name Is Khan",                   "Drama Social",                   "A Muslim man stands up for his community after September 11 attacks",     8.0),
        ("Chak De India",                     "Drama Sport",                    "An Indian coach leads the women national hockey team to victory",         8.2),
        ("Black",                             "Drama",                          "A teacher helps a deaf and blind girl discover the world around her",     8.1),
        ("Rockstar",                          "Drama Music Romance",            "A musician falls in love but struggles to find his identity and path",    7.9),
        ("Tamasha",                           "Drama Romance",                  "A man has two sides to his personality and struggles to find meaning",    7.6),
        ("Jab We Met",                        "Drama Romance",                  "A woman travels alone from Punjab and meets an unexpected companion",     7.5),
        ("Highway",                           "Drama Thriller",                 "A girl taken on a road trip against her will discovers unexpected freedom",7.6),
        ("Udta Punjab",                       "Drama Thriller",                 "Youth in Punjab struggle with drug addiction and its social consequences", 7.6),
        ("Haider",                            "Drama Thriller",                 "A prince seeks revenge for his father and falls for Ophelia in Kashmir",  7.8),
        ("Omkara",                            "Drama Thriller",                 "A man in power becomes corrupted in this Othello adaptation set in UP",   7.8),
        ("Maqbool",                           "Crime Drama",                    "A village man rises to power in the Mumbai underworld in this drama",     7.6),
        ("Drishyam 2",                        "Crime Thriller Drama",           "A man continues protecting his family secrets in this gripping sequel",   7.5),
        ("Bhool Bhulaiyaa 2",                "Horror Comedy",                  "A priest helps people dealing with supernatural problems comedy horror",  7.5),
        ("Brahmastra",                        "Action Fantasy",                 "A superhero with ancient fire powers fights mythological demons",         6.5),
        ("Vikram Vedha",                      "Action Crime Thriller",          "Two men mirror each other in this gripping action crime thriller",        7.8),
        ("Shershaah",                         "Action Drama Biography",         "An army captain leads troops against Pakistani militants based on true events",8.0),
        ("Kesari",                            "Action Drama History",           "Sikhs fight the British at Saragarhi against overwhelming odds in 1897", 7.4),
        ("Batla House",                       "Action Thriller",                "A police officer investigates a militant attack in Delhi action thriller",  7.4),
        ("Mission Mangal",                    "Drama Biography",                "Scientists at ISRO work to launch India first mission to Mars",           7.5),
        ("Toilet Ek Prem Katha",             "Comedy Drama Social",            "A man builds a toilet for his wife as she threatens to leave him",        6.3),
        ("Rustom",                            "Action Thriller",                "A naval officer is convicted of murder and seeks justice with his lawyer", 6.8),
        ("Airlift",                           "Drama Biography",                "An Indian man rescues hundreds of people stranded in Kuwait during war",  7.9),
        ("Baby",                              "Action Thriller",                "An intelligence officer hunts down terrorists threatening India",          7.2),
        ("Ek Tha Tiger",                      "Action Thriller",                "An RAW agent goes undercover to protect a nuclear scientist action",       6.5),
        ("Tiger Zinda Hai",                   "Action Thriller",                "An RAW agent continues his dangerous missions across the world",           6.0),
        ("War",                               "Action Thriller",                "A soldier and a spy race against each other in an action thriller",       6.9),
        ("Pathaan",                           "Action Thriller",                "A Bollywood superstar goes on a mission to protect Indians abroad",       5.9),
        ("Jawan",                             "Action Drama",                   "A soldier goes rogue seeking revenge while the government hunts him down", 7.0),
        ("Animal",                            "Action Drama",                   "A man fights to gain his fathers approval through extreme means drama",    5.5),
        ("Dunki",                             "Drama Comedy",                   "A group of friends try to illegally immigrate to UK in this comedy drama", 5.8),
        ("Fighter",                           "Action Thriller",                "Indian Air Force pilots fight enemies in a high octane action film",       5.6),
        ("12th Fail",                         "Drama Biography",                "A rural boy beats all odds to clear the UPSC examination against poverty", 8.9),
        ("Sam Bahadur",                       "Drama Biography",                "The story of Field Marshal Sam Manekshaw and the 1971 Indo-Pak war",      7.8),
        ("Bheed",                             "Drama Social",                   "A journalist exposes migrant worker deaths during the pandemic drama",     6.5),
        ("Gulmohar",                          "Drama",                          "An elderly couple navigate changing family dynamics and memory loss drama", 7.5),
        ("Rocky Aur Rani",                    "Drama Romance Comedy",           "Two opposites fall in love and navigate each others different worlds",     7.0),
        ("Zara Hatke Zara Bachke",           "Romance Comedy Drama",           "A couple navigate their relationship in a sweet romantic comedy drama",    6.9),
        ("Satyaprem Ki Katha",               "Drama Romance",                  "A man fights to win over a woman who is carrying emotional trauma romance", 7.5),
        ("Tu Jhoothi Main Makkaar",          "Comedy Drama Romance",           "Two people who help others break up fall in love with each other comedy",  6.5),
        ("OMG 2",                             "Drama Social Comedy",            "A man fights for sexual education rights in schools drama social comedy",  8.0),
        ("Dream Girl 2",                      "Comedy Drama",                   "A man disguises himself as a woman and creates comedy chaos drama",        5.5),
        ("Bhediya",                           "Horror Comedy",                  "Two werewolves cause comedic chaos in a small hill station horror comedy", 6.6),
        ("An Action Hero",                    "Action Comedy",                  "A film star goes on the run after a mistaken identity mix-up comedy",      7.0),
        ("Doctor G",                          "Comedy Drama",                   "A male gynaecology student navigates hilarious situations in hospital",    6.5),
        ("Govinda Naam Mera",                "Comedy Drama Thriller",          "A film star and his manager deal with ghost trouble comedy thriller",      6.5),
        ("Dasvi",                             "Comedy Drama",                   "A strict politician goes to jail and learns humanity from the prisoners",   7.3),
        ("Luka Chuppi",                       "Comedy Drama Romance",           "A couple live together before marriage and face comic family situations",   6.9),
        ("Stree",                             "Horror Comedy",                  "A town is terrorized by a female ghost who abducts men in this comedy",   7.5),
        ("Badhaai Ho",                        "Comedy Drama",                   "A middle aged couple announce pregnancy and cause family comedy chaos",    8.1),
        ("Bala",                              "Comedy Drama",                   "A man goes bald prematurely and must deal with social insecurities comedy", 7.1),
        ("Chhichhore",                        "Comedy Drama",                   "A group of friends revisit their college days through their children",     8.1),
        ("Super 30",                          "Drama Biography",                "A mathematician trains underprivileged students for the IIT entrance exam", 7.3),
        ("Tanhaji",                           "Action Drama History",           "A Maratha warrior fights the Mughal empire to recapture a fort action",   7.0),
        ("Thappad",                           "Drama Social",                   "A woman seeks divorce after her husband slaps her once in a drama",        7.5),
        ("Panga",                             "Drama Sport",                    "A former kabaddi champion returns to the sport after becoming a mother",   7.4),
        ("Shakuntala Devi",                   "Biography Drama",                "The story of the human computer Shakuntala Devi and her life journey",     7.2),
        ("Gunjan Saxena",                     "Biography Drama",                "The story of the first woman combat pilot in the Indian Air Force",        7.1),
        ("Mimi",                              "Comedy Drama",                   "A woman agrees to be a surrogate for a foreign couple in this drama",      7.6),
        ("Sardar Udham",                      "Drama Biography History",        "An Indian revolutionary plans to assassinate a British officer after Jallianwala",8.4),
        ("Gehraiyaan",                        "Drama Thriller Romance",         "Two cousins find their lives upended by attraction and dark secrets",      5.5),
        ("Darlings",                          "Comedy Drama Thriller",          "A woman and her mother deal with an abusive husband in dark comedy drama", 7.5),
        ("Monica O My Darling",              "Comedy Crime Thriller",          "A man plans to murder his wife and gets entangled in a complex conspiracy", 7.5),
        ("Dobaaraa",                          "Thriller Sci-Fi",                "A woman discovers she can communicate through time via an old television", 6.5),
        ("Freddy",                            "Thriller Drama",                 "A dentist with dark secrets falls obsessively in love with a woman thriller",6.5),
        ("Bhakshak",                          "Drama Social",                   "A journalist exposes a shelter home abuse scandal in this social drama",    7.8),
        ("Article 370",                       "Drama Thriller",                 "The events leading to the revocation of Article 370 in Kashmir drama",     7.5),
        ("Maidaan",                           "Drama Sport Biography",          "The story of Indian football coach Syed Abdul Rahim and Indian football",  7.5),
        ("Bade Miyan Chote Miyan",           "Action Comedy",                  "Two comedians go on separate missions in this buddy action comedy film",    3.5),
        ("Crew",                              "Comedy Thriller",                "Three flight attendants get caught up in a smuggling scandal thriller",     6.5),
        ("Stree 2",                           "Horror Comedy",                  "The ghost terrorizing the town returns for another round of horror comedy", 8.5),
    ]

    # ── TELUGU MOVIES (100) ───────────────────────────────────────────
    telugu = [
        ("Baahubali The Beginning",           "Action Adventure Fantasy",       "A prince fights to reclaim his kingdom from a tyrant in a grand epic",    8.1),
        ("Baahubali The Conclusion",          "Action Adventure Fantasy",       "The conclusion of the prince battle against the tyrant with massive war",  8.4),
        ("Arjun Reddy",                       "Drama Romance",                  "A passionate rebellious medical student falls in love with a senior doctor",8.2),
        ("Jersey",                            "Drama Sport Romance",            "A failed cricketer revives his career and inspires his son emotionally",   8.6),
        ("Ala Vaikunthapurramuloo",           "Action Comedy Romance",          "A young man fights for his family happiness with energy and comedy",       7.9),
        ("Pushpa The Rise",                   "Action Crime Drama",             "A red sandalwood smuggler rises to power in Andhra Pradesh forests",       7.8),
        ("RRR",                               "Action Adventure Drama",         "Two childhood friends fight the British colonial rule with action emotion", 7.9),
        ("Magadheera",                        "Action Fantasy Adventure",       "A warrior uses a magical sword to fight an evil king in a fantasy world",  7.7),
        ("Pokiri",                            "Action Crime Thriller",          "A police officer goes undercover to catch a dangerous criminal gang",       7.9),
        ("Okkadu",                            "Action Romance Drama",           "A common man fights a powerful villain to save the girl he loves",          7.8),
        ("Athadu",                            "Action Crime Thriller",          "A carefree man gets entangled in a murder plot while hiding from his past", 7.8),
        ("Eega",                              "Action Fantasy Drama",           "A murdered boy comes back as a fly to take revenge on his killer",          8.4),
        ("Julayi",                            "Action Comedy",                  "A carefree guy gets caught in a murder investigation while falling in love", 7.5),
        ("Mirchi",                            "Action Romance Drama",           "A police officer fights the villain who killed his father to save a village",7.8),
        ("Srimanthudu",                       "Action Drama Romance",           "A self-made wealthy man strives to give his family a better life fighting enemies",7.6),
        ("Fidaa",                             "Drama Romance",                  "A girl from Telangana falls in love with a carefree boy from Vizag",        7.9),
        ("Geetha Govindam",                   "Drama Romance Comedy",           "A college boy and girl fall in love over misunderstandings and comedy",     7.8),
        ("Saaho",                             "Action Thriller",                "A cop investigates a case involving a billionaire and multiple murders",     6.2),
        ("Maharshi",                          "Drama Romance",                  "A software engineer quits his job to become a farmer and helps his father", 7.6),
        ("Vakeel Saab",                       "Drama Courtroom",                "A lawyer fights for justice for a woman wronged by the system",             7.5),
        ("Bheemla Nayak",                     "Action Drama",                   "A cop fights a criminal who killed his mentor in this mass action drama",   7.6),
        ("Radhe Shyam",                       "Drama Romance Sci-Fi",           "Two lovers separated by fate are reunited in this romantic sci-fi drama",   7.2),
        ("Bangarraju",                        "Drama Comedy Romance",           "A man and his grandmother go on a fun adventure together in this drama",    7.3),
        ("Acharya",                           "Action Drama",                   "A social reformer fights powerful enemies in this action drama film",        6.8),
        ("Liger Telugu",                      "Action Drama",                   "A boxer fights against all odds to become a champion action drama",          7.2),
        ("Karthikeya 2",                      "Adventure Drama Mystery",        "A man follows mysterious clues to uncover a hidden divine treasure",         7.9),
        ("Sita Ramam",                        "Drama Romance War",              "Two people fall in love during the Indo-Pakistani war of 1971 romance war",  8.3),
        ("Major",                             "Action Drama Biography",         "A soldier goes on a dangerous mission to save his colleagues from terrorists",7.6),
        ("Pushpa The Rule",                   "Action Crime Drama",             "The sequel to the smuggler story with more action and drama crime action",   7.5),
        ("Kalki 2898 AD",                     "Action Sci-Fi Fantasy",          "A futuristic warrior is chosen to fight a cosmic battle in 2898 AD",         7.8),
        ("Devara",                            "Action Drama Thriller",          "A rugged man fights land sharks to protect his village action drama",         7.3),
        ("Guntur Kaaram",                     "Drama Family",                   "A son fights to restore his father legacy in this emotional family drama",    7.0),
        ("Saindhav",                          "Action Thriller",                "A cop goes undercover to eliminate a dangerous criminal gang action",          7.2),
        ("Hanu Man",                          "Action Fantasy Drama",           "A young man with extraordinary Hanuman powers fights supernatural evil",      8.2),
        ("Eagle Telugu",                      "Action Thriller",                "A cop fights a dangerous criminal network in this action thriller film",      7.3),
        ("Skanda",                            "Action Drama",                   "A hero fights for justice against a crime infested city action drama",        7.0),
        ("Tiger Nageswara Rao",               "Action Crime Thriller",          "A cop hunts a notorious criminal based on a true story action crime",         7.5),
        ("Hi Nanna",                          "Drama Romance",                  "A father bonds with his daughter during a vacation drama romance film",       7.8),
        ("Premalu",                           "Drama Romance Comedy",           "Two people fall in love in a simple small town in this sweet romance comedy", 7.6),
        ("Extra Ordinary Man",                "Comedy Drama",                   "A man discovers hidden talents and wins the girl of his dreams comedy",       7.2),
        ("Naa Saami Ranga",                   "Drama Comedy Romance",           "A couple navigate misunderstandings in this fun family drama comedy romance", 7.5),
        ("Virupaksha",                        "Horror Thriller Drama",          "A village faces a supernatural entity unleashed after an excavation horror",  7.7),
        ("Waltair Veerayya",                  "Action Comedy Drama",            "A middle class family navigates comedy and chaos action comedy drama",         7.4),
        ("Veera Simha Reddy",                 "Action Drama",                   "A mass hero fights corrupt politicians and gangsters in this action drama",   7.5),
        ("The Ghost",                         "Action Thriller",                "A ghost takes revenge on those who wronged him in a past life thriller",      7.0),
        ("Bimbisara",                         "Action Fantasy Drama",           "A medieval prince is reborn in the modern world with his powers intact",      7.8),
        ("Dhamaka Telugu",                    "Action Comedy Drama",            "A rowdy cop and a smooth cop solve a crime together action comedy drama",     7.2),
        ("Pakka Commercial",                  "Action Comedy Drama",            "A hero fights for rights of farmers against corporate greed action comedy",   7.5),
        ("Konda Polam",                       "Drama Rural",                    "A farmer fights for his land and way of life against greedy developers rural",7.5),
        ("Uppena",                            "Drama Romance",                  "A boy from a fishing village falls in love in a pure and emotional romance",  7.8),
        ("Love Story Telugu",                 "Drama Romance",                  "A man fights to prove his love and win back his girlfriend romantic drama",   7.5),
        ("Ante Sundaraniki",                  "Comedy Drama Romance",           "A simple couple navigate life challenges in this heartwarming comedy romance", 7.5),
        ("Naandhi",                           "Drama Courtroom",                "A lawyer takes on a sexual assault case in this intense courtroom drama",     7.3),
        ("Most Eligible Bachelor",            "Drama Romance Comedy",           "A couple navigate their interfaith relationship in this comedy romance film",  7.5),
        ("Tuck Jagadish",                     "Drama Comedy",                   "A joint family goes on misadventures in this family comedy drama film",       7.3),
        ("Wild Dog",                          "Action Thriller",                "A cop investigates a wildlife smuggling operation in this action thriller",    7.0),
        ("Krack",                             "Action Drama",                   "An undercover cop fights a dangerous crime syndicate action drama film",      7.3),
        ("Akhanda",                           "Action Drama",                   "A special warrior fights supernatural and human evil forces action drama",    7.5),
        ("Khiladi",                           "Action Thriller",                "A special ops team carries out a covert mission in this action thriller",     7.5),
        ("Ramarao On Duty",                   "Action Drama Thriller",          "A government officer fights corruption in this serious action thriller drama", 7.3),
        ("Aadavallu Meeku Johaarlu",          "Drama Comedy Romance",           "A romantic couple fight for their relationship in a comedy romance drama",    7.3),
        ("Sarkaru Vaari Paata",               "Action Drama",                   "A hero and villain mirror each other in this action crime thriller drama",    7.5),
        ("F3 Fun and Frustration",            "Comedy Drama",                   "Three friends go on a fun filled road trip in this comedy drama film",        7.5),
        ("Dasara Telugu",                     "Action Drama",                   "A village boy rises to power in an emotional mass entertainer action drama",  7.5),
        ("Bhagavanth Kesari",                 "Action Drama",                   "A man fights to protect his granddaughter and family action drama film",      7.4),
        ("Tillu Square",                      "Comedy Drama",                   "A story of a couple navigating their arranged marriage romance comedy sequel", 7.3),
        ("Yatra 2",                           "Drama Biography",                "A politician and his family face challenges in this political drama sequel",   7.5),
        ("Bhimaa",                            "Action Drama",                   "A story exploring life struggles of a common man in Telangana rural drama",   7.4),
        ("Mem Famous",                        "Comedy Drama",                   "A group of friends make a film in this fresh and funny comedy drama film",    7.5),
        ("Ori Devuda",                        "Comedy Drama",                   "A couple go through misunderstandings and eventually reconcile comedy drama",  7.4),
        ("Alluri",                            "Action Drama",                   "A crime drama exploring gun culture and its impact on a village action drama", 7.4),
        ("Bedurulanka 2012",                  "Drama Thriller",                 "A village battles rising floodwaters and human evil in this drama thriller",  7.5),
        ("Michael Telugu",                    "Action Drama",                   "A cop fights human traffickers to save children in this action drama film",   7.5),
        ("Sehari",                            "Drama Rural",                    "A village battle over land rights in this emotional rural Telugu drama film",  7.3),
        ("Kushi Telugu",                      "Drama Romance Comedy",           "A couple navigate misunderstandings and fall in love comedy romance drama",    7.3),
        ("Custody",                           "Action Drama Thriller",          "A cop fights corruption to get custody of a child in this action thriller",   7.3),
        ("The Warrior Telugu",                "Action Thriller",                "An undercover officer fights a criminal syndicate action thriller drama",      7.3),
        ("Sreekaram",                         "Drama Rural Social",             "A village fights for water rights in this emotional rural social drama film",  7.3),
        ("Cinema Bandi",                      "Comedy Drama",                   "A group of friends make a film in this fresh Telugu comedy drama film",       7.5),
        ("Mallesham",                         "Drama Biography",                "A weaver inventor creates a machine to help artisans in this biography drama", 8.0),
        ("Colour Photo",                      "Drama Romance Social",           "Two people from different castes fall in love in this social drama film",      7.8),
        ("Uma Maheswara Ugra Roopasya",       "Comedy Drama",                   "A timid man transforms after facing personal tragedy in this comedy drama",   7.6),
        ("Falaknuma Das",                     "Action Drama",                   "An auto driver fights the system to save his friend in this action drama",    7.5),
        ("Brochevarevarura",                  "Comedy Crime Drama",             "Four friends get entangled in a kidnapping plot in this comedy crime drama",  7.5),
        ("Agent Sai Srinivasa",               "Comedy Crime Drama",             "An aspiring detective solves crimes in this funny comedy crime drama film",   7.3),
        ("Zombie Reddy",                      "Horror Comedy",                  "A zombie outbreak in Rayalaseema leads to comedy and horror in this film",    6.5),
        ("HIT The First Case",                "Crime Thriller Drama",           "A cop investigates a missing person case that turns into a complex thriller",  7.3),
        ("HIT The Second Case",               "Crime Thriller Drama",           "A detective investigates a serial killer case in this gripping crime thriller", 7.3),
        ("Swathimuthyam",                     "Drama Romance",                  "A simple innocent man falls in love in this heartwarming Telugu romance drama", 8.0),
        ("Pushpaka Vimanam",                  "Comedy Drama",                   "A man poses as a rich person to win over a girl in this comedy drama film",   7.5),
        ("Ravanasura",                        "Action Thriller Drama",          "A lawyer fights for justice while hiding a dark secret in this action thriller",7.3),
        ("Lucky Baskhar",                     "Drama Thriller",                 "A bank employee gets caught in a dangerous financial fraud thriller drama",    7.9),
        ("Amaran Telugu",                     "Action Drama Biography",         "The story of Major Mukund Varadarajan who died fighting militants in Kashmir", 8.3),
        ("Drishyam Telugu",                   "Crime Thriller Drama",           "A man protects his family from police investigation after an accidental death", 8.2),
        ("Evaru",                             "Crime Thriller Mystery",         "A police officer investigates a rape accusation with shocking twists thriller", 7.8),
        ("Butta Bomma",                       "Drama Romance",                  "Two souls connect across different time periods in this romantic drama film",  7.4),
        ("Pelli SandaD",                      "Comedy Drama Romance",           "A couple face funny situations during their wedding celebrations comedy drama", 7.3),
        ("Thellavarithe Guruvaram",           "Drama Romance",                  "A young man must get married within a week in this fun romantic drama film",  7.3),
        ("Gam Gam Ganesha",                   "Comedy Drama",                   "A family comedy drama about the celebrations of Ganesh festival film",         7.3),
        ("Dasara",                            "Action Drama",                   "A man rises from poverty to become a powerful figure in the coal mines action", 7.5),
    ]

    # Build DataFrame
    def parse(lst, lang):
        titles  = [x[0] for x in lst]
        genres  = [x[1] for x in lst]
        descs   = [x[2] for x in lst]
        ratings = [x[3] for x in lst]
        langs   = [lang] * len(lst)
        return titles, langs, genres, descs, ratings

    et, el, eg, ed, er = parse(english, "English")
    ht, hl, hg, hd, hr = parse(hindi,   "Hindi")
    tt, tl, tg, td, tr = parse(telugu,  "Telugu")

    return pd.DataFrame({
        "title":       et + ht + tt,
        "language":    el + hl + tl,
        "genres":      eg + hg + tg,
        "description": ed + hd + td,
        "rating":      er + hr + tr,
    })
